### ISSUE TITLE
Page number set as null for the related images endpoint

### ISSUE THREAD

**Issue by chrisbartoloburlo** [WordPress/openverse-api#931] opened 2022-09-20 11:15 UTC
## Description
Wrong page number when requesting related images using the `images/{identifier}/related/` endpoint.

## Reproduction
1. `just up`
2. Run `curl -v \
  --request GET \
  --url 'http://localhost:50280/v1/images/5f9ed3ba-b762-459e-9165-094470dc4805/related/?format=json'`
3. Notice the `page` parameter set as `null`: {"result_count":767,"page_count":1,"page_size":10,"page":null,"results":[...]}

## Resolution
- [x] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment] 2022-09-20 13:42
I get `page:1` as the result of that request @chrisbartoloburlo. Did you try it in a fresh environment? After doing `just recreate`?

**Comment by chrisbartoloburlo** [comment] 2022-09-20 13:53
I executed `just recreate` and tried the request once again. However, I got the same output with `"page"=1`.

**Comment by AetherUnbound** [comment] 2022-09-20 20:50
I've set the priority of this issue to "high" because it seems like it may be a bug in the API that should be addressed. If this ends up being difficult to replicate or ends up being an issue that's smaller in scope, we can reduce the priority. Thank you again for raising this Christian!

**Comment by AetherUnbound** [comment] 2022-09-21 05:19
I also see `"page": 1` when I run `curl -s --request GET \ --url 'http://localhost:50280/v1/images/5f9ed3ba-b762-459e-9165-094470dc4805/related/?format=json' | jq ".page"`. @WordPress/openverse-api is anyone else able to reproduce what @chrisbartoloburlo is seeing?

**Comment by chrisbartoloburlo** [comment] 2022-09-21 06:47
@AetherUnbound do you also get `"page":1` when you run `curl -s --request GET \ --url 'https://api.openverse.engineering/v1/images/5f9ed3ba-b762-459e-9165-094470dc4805/related/?format=json' | jq ".page"`?

**Comment by AetherUnbound** [comment] 2022-09-21 17:42
Woah! Great find Christian! No, I am also getting `null` on that one 😮 This is the case in both staging and prod:
* https://api-dev.openverse.engineering/v1/images/0aff3595-8168-440b-83ff-7a80b65dea42/related/
* https://api.openverse.engineering/v1/images/0aff3595-8168-440b-83ff-7a80b65dea42/related/

@chrisbartoloburlo if you run `git checkout main && git pull` then `just recreate`, do you see the same behavior locally?

**Comment by AetherUnbound** [comment] 2022-09-21 17:45
I suspect that this was addressed in #868, which is merged and slated for release this week. We can see if this issue is addressed in production after the deployment.

**Comment by AetherUnbound** [comment] 2022-09-21 17:49
Sorry for the multiple posts, I ran `git checkout v2.5.12 && just build && just up` then ran the following:

```bash
$ curl -s --request GET \ --url 'http://localhost:50280/v1/images/5f9ed3ba-b762-459e-9165-094470dc4805/related/?format=json' | jq ".page"
null
```

So this has been addressed as of v2.5.13, which we'll be deploying this week!

**Comment by AetherUnbound** [comment] 2022-09-21 20:27
API [v2.5.13](https://github.com/WordPress/openverse-api/releases/tag/v2.5.13) has been deployed and the `page` is now showing up correctly! I'll go ahead and close this issue, thanks again for raising it Christian 😄

**Closed by AetherUnbound** 2022-09-21 20:27 UTC
Labels: 🟧 priority: high, 🛠 goal: fix, 🕹 aspect: interface, 🐍 tech: python, 🔧 tech: django

**Comment by krysal** [comment] 2022-09-21 20:32
Great find @chrisbartoloburlo! Thanks for communicating this :)
