### ISSUE TITLE
An attempt to get `accuracy` key results in SystemExit

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#978] opened 2022-10-13 07:21 UTC
## Sentry link

https://sentry.io/share/issue/41c5ce98e9184ad192e43814b3f23abf/

## Description

`media_serializer` calls `super.to_representation()`. For `tags` field, when the `tag` does not contain `accuracy`, it can raise an error that breaks the app and causes a `SystemExit`.

I am not sure why it would look for `accuracy` in tags even though `accuracy` is set as not required:
```
TagSerializer(allow_null=True, help_text='Tags with detailed metadata, such as accuracy.', many=True):
    name = CharField(help_text='The name of a detailed tag.')
    accuracy = FloatField(help_text='The accuracy of a machine-generated tag. Human-generated tags do not have an accuracy field.', required=False)
```

## Reproduction

I will try to reproduce and update the issue.

**Comment by dhruvkb** [comment] 2022-10-18 19:50
Since this error
- occurred only once in the last month
- did not reappear in the five days since the first incident
- shows an incorrect traceback where the uncaught exception has a `catch` clause
- cannot be reproduced by making the same request that caused it in the first place

I'm lowering the priority to low. If it still doesn't appear in the future, we'll close it.

**Comment by krysal** [comment] 2022-10-24 22:16
I ignored it in Sentry until it appears 10 times more. Reopen in that case.

**Closed by krysal** 2022-10-24 22:16 UTC
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code, 🐛 tooling: sentry
