### ISSUE TITLE
Gunicorn workers unexpected quitting in production

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#489] opened 2022-01-28 21:48 UTC
## Description

Gunicorn workers are unexpected quitting in production.

https://sentry.io/share/issue/061ba99fc3df4c23bdb7643d337bbda0/

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment] 2022-01-28 22:13
Based on the traceback, it looks like this is happening in the `grequests.map` function where image validation of the related images is occurring:
![image](https://user-images.githubusercontent.com/10214785/151628677-caefc09a-fff8-4cf2-b99c-6b81ae491bfc.png)

This seems potentially related to #486 - my initial guess is that the workers used in `grequests` are either timing out or running out of memory. Will continue to investigate

**Comment by AetherUnbound** [comment] 2022-01-28 22:26
This seems to corroborate my hunch: https://stackoverflow.com/q/28223414/3277713
If the worker doesn't report back in enough time and eventually hangs, it gets an abort signal. This is also discussed in getsentry/raven-python#675.

**Comment by sarayourfriend** [comment] 2022-04-25 15:56
We have so many SystemExit errors in sentry. The thumbnail route in particular seems to be problematic for this.

The stack trace is maddening, there's a clear circular middleware issue going on but I'm not sure how to debug it. More of that covered in #521.

**Comment by AetherUnbound** [comment] 2022-08-17 00:00
Updated public share link: https://sentry.io/share/issue/061ba99fc3df4c23bdb7643d337bbda0/

**Comment by AetherUnbound** [comment] 2022-08-17 18:16
We have not seen this issue appear since we released the performance improvements that came alongside [v2.5.10](https://github.com/WordPress/openverse-api/releases/tag/v2.5.10) recently. We believe this was caused by `grequests` & requests to Elasticsearch timing out, which is no longer occurring. Closing this issue for now!

**Closed by AetherUnbound** 2022-08-17 18:16 UTC
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code, 🐛 tooling: sentry

**Comment by sarayourfriend** [comment] 2022-08-17 18:28
> We believe this was caused by grequests & requests to Elasticsearch timing out, which is no longer occurring

We do still use grequests and grequests does not make requests to ES. I'm not sure what to make of the relationship implied here. Was grequests somehow being affected by ES time outs? The only relationship I can think of is that because we've reduced the maximum pagination depth we're just making less validation requests overall and therefore utilizing grequests a lot less than before.

**Comment by AetherUnbound** [comment] 2022-08-17 19:41
Ah, apologies! Yes that would make sense.
