### ISSUE TITLE
`MEDIA_INDEX_MAPPING` not retrievable from settings

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#845] opened 2022-08-03 12:31 UTC
## Sentry link

https://sentry.io/share/issue/43ef4374b5b142868bca159d47506bb3/

## Description

https://github.com/WordPress/openverse-api/blob/419082f155372ee05bdc5c4261feea06906eb49f/api/catalog/settings.py#L21

Something isn't working in this line. It is causing the settings object not to include `MEDIA_INDEX_MAPPING`.

Introduced in https://github.com/WordPress/openverse-api/pull/712

## Suggested solution

Revert ES configuration refactors.

**Comment by sarayourfriend** [comment] 2022-08-03 12:33
I suggest reverting the ES configuration refactors to keep only the existing large scale refactors in the current deploy. We're trying to do too much in a single version change and we already have risky changes. If we can cut out some of these refactors to isolate only the changes necessary to be able to debug production ES CPU usage (which we've been blocked on for several weeks due to another big refactor in the search controller area) then we can move forward with more confidence.

**Comment by zackkrida** [comment] 2022-08-03 13:17
Did we set the environment variables used by this PR in the staging environment?

```
IMAGE_INDEX_NAME="image"
AUDIO_INDEX_NAME="audio"
```

Perhaps if not, the error with the code is setting the _default value_ and by passing these it would work.

**Comment by sarayourfriend** [comment] 2022-08-03 13:20
To clarify where this is happening, by the way, because it's non-obvious from Sentry due to misconfiguration causing it to show the `local` environment.

Unless someone is actually causing this error locally, it can only be happening in staging API because production doesn't have this code yet.

**Comment by krysal** [comment] 2022-08-03 13:33
@zackkrida No, the two environment variables added in the staging deployment were only `LOG_LEVEL` and `ALLOWED_HOSTS` [[Ref](https://github.com/WordPress/openverse-infrastructure/pull/166/files#diff-af38c03926a84ad7d785e8e95d033917e338220de291b87ffd8ff0407e8aa352)].

**Comment by dhruvkb** [comment] 2022-08-03 14:14
I'm unable to reproduce this locally on a fresh copy on `main`. It's very hard to see why this would raise errors in staging but work normally on a local copy.

**Comment by AetherUnbound** [comment] 2022-08-03 15:21
While we don't have the sentry alerts separated by environment (to-be-deployed), I cross-referenced a few of the pieces of this alert against others.

1. The breadcrumb for an earlier ES hit points to `es:9200`, which is the URL we use in the local development stack. In production, this is `http://openverse-elasticsearch-prod.private:9200`
![image](https://user-images.githubusercontent.com/10214785/182645196-975ba4fb-cc09-4986-adb5-f4aeef73ef3e.png)
![image](https://user-images.githubusercontent.com/10214785/182645233-3cd71d98-d393-4fec-9e82-cdbad2a1dfea.png)

2. The `server_name` field corresponds to the Docker container ID in which the API is running. The `server_name` in this alert is `5d3b4c585574`. The current container IDs for staging are:
- `eb1035da4ee6`
- `29f45c7a2970`
- `23b301981cf1`
- `11808dc2fd0c`
- `1225f87be930`


Both of these factors lead me to believe this occurred locally (rather than in staging/prod).

**Comment by zackkrida** [comment] 2022-08-03 17:18
Closing due to irreproducibility.

**Closed by zackkrida** 2022-08-03 17:18 UTC
Labels: 🛠 goal: fix, 💻 aspect: code
